repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: no-commit-to-branch
    args: [--branch, master]
    exclude: scripts/|docs/|tests/
  - id: check-yaml
    exclude: scripts/|docs/|tests/
  - id: end-of-file-fixer
    exclude: scripts/|docs/|tests/
  - id: trailing-whitespace
    exclude: scripts/|docs/|tests/
  - id: debug-statements
    exclude: scripts/|docs/|tests/
  - id: fix-encoding-pragma
    exclude: scripts/|docs/|tests/
  - id: mixed-line-ending
    exclude: scripts/|docs/|tests/
- repo: https://github.com/ambv/black
  rev: 24.2.0
  hooks:
  - id: black
    exclude: scripts/|docs/|tests/
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    exclude: scripts/|docs/|tests/
- repo: local
  hooks:
    - id: nbstripout
      name: nbstripout with keep-output
      entry: |
        python -m nbstripout --keep-output $@
      language: system
      files: \.ipynb$
