version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
sphinx:
   configuration: docs/conf.py
conda:
  environment: docs/rtdenv.yml
python:
   install:
      - method: pip
        path: .
