package:
    name: pydna
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  include_recipe: False
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  git_url: .

requirements:
    build:
        - python {{ python }}
        - setuptools
        - setuptools_scm
        - pytest-runner
    run:
        - python {{ python }}
        - appdirs
        - biopython >=1.78
        - networkx
        - prettytable
        - pyparsing
        - requests
        - ipython
        - jupyter
        - scipy
        - matplotlib
        - pillow
        - pydrive2

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-doctestplus
    - requests-mock
    - nbval
    - coverage
    - pydrive2
  imports:
    - pydna
  source_files:
    - tests
    - src
    - src/pydna
about:
  home: https://github.com/BjornFJohansson/pydna
  summary: Representing double stranded DNA and simulating cloning, homologous recombination, Gibson assembly, Gel electrophoresis etc.
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
extra:
  maintainers:
   - "Björn Johansson <bjorn_johansson@bio.uminho.pt>"
