package:
    name: pydna
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  include_recipe: False
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  git_url: .

requirements:
    build:
        - python {{ python }}
        - setuptools>=59.2.0
        - setuptools_scm>=6.3.2
    run:
        - python {{ python }}
        - appdirs>=1.4.4
        - biopython >=1.79
        - networkx>=2.6.3
        - prettytable>=3.2.0  # todo replace with tabulate at some point

        - pyparsing>=2.4.7    # optional
        - requests>=2.26.0    # optional
        - scipy>=1.8.0        # optional
        - matplotlib>=3.4.3   # optional
        - pillow>=8.4.0       # optional
        - CAI>=1.0.3          # optional

test:
  requires:
    - pytest>=4.6.11
    - pytest-cov>=3.0.0
    - pytest-doctestplus>=0.12.0
    - requests-mock>=1.9.3
    - nbval>=0.9.6
    - coverage>=6.1.2
  imports:
    - pydna
  source_files:
    - tests
    - src
    - src/pydna
about:
  home: https://github.com/BjornFJohansson/pydna
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Representing double stranded DNA and simulating cloning, homologous recombination, Gibson assembly, Gel electrophoresis etc.
  description: Representing double stranded DNA and simulating cloning, homologous recombination, Gibson assembly, Gel electrophoresis etc.
  doc_url: https://pydna.readthedocs.io
  dev_url: https://github.com/BjornFJohansson/pydna
extra:
  maintainers:
   - "Björn Johansson <bjorn_johansson@bio.uminho.pt>"
