name: pydna_build_environment
channels:
- conda-forge
- defaults
- BjornFJohansson
dependencies:
- python
- appdirs
- biopython
- prettytable
- networkx
- pyparsing
- mpldatacursor

- setuptools
- twine
- pip
- anaconda-client
- conda-build
- conda-verify
