name: pydna_build_environment
channels:
- conda-forge
- defaults
- bjornfjohansson

dependencies:
- python

- appdirs
- biopython==1.80
- networkx
- prettytable
- pyparsing
- CAI
- regex

- mamba
- poetry
- pip:
    - poetry-dynamic-versioning
- build
- twine
- anaconda-client
- conda-build
- conda-verify
