name: pydna_build_environment
channels:
- conda-forge
- bjornfjohansson

dependencies:
- python==3.11

- appdirs
- biopython==1.80
- networkx
- prettytable
- pyparsing
- CAI
- regex

- pip
- poetry
- pip:
    - poetry-dynamic-versioning
- mamba
- conda-build
