name: pydna_build_environment
channels:
- conda-forge
- defaults
- BjornFJohansson
dependencies:
- python

- appdirs
- biopython
- networkx
- prettytable
- pyparsing
- CAI
- regex

- setuptools
- twine
- pip
- anaconda-client
- conda-build
- conda-verify
- pydrive2
