name: pydna_build_environment
channels:
- conda-forge
- defaults
- bjornfjohansson

dependencies:
- python

- appdirs
- biopython==1.80
- networkx
- prettytable
- pyparsing
- CAI
- regex

- setuptools
- twine
- pip
- anaconda-client
- conda-build
- conda-verify
