name: pydna_build_environment
channels:
- conda-forge
- defaults
- BjornFJohansson
dependencies:
- python
- appdirs
- biopython
- prettytable
- networkx
- pyparsing

- setuptools
- twine
- pip
- anaconda-client
