name: pydna_build_environment
channels:
- conda-forge
dependencies:
- python==3.11
- appdirs
- biopython>=1.80,<2.0
- networkx
- prettytable
- pyparsing
- bjornfjohansson::CAI
- poetry
- pip
- pip:
    - poetry-dynamic-versioning