# random DNA generator http://www.faculty.ucr.edu/~mmaduro/random.htm


def fwdp(lst):
    primers = []
    for s in lst:
        primers.append(s[:20])
    return primers


seqlist = [
    "TTAGTGTAGGTTCTGACCGATACCTGCTTCGTTGAGAACTCACAATTTTACAACTGGGGACATAATCCCTACGCCCATCATCTACTCGCGTCCCTGTGGCTCCAGTTCATGTAATGGGAGAGTATCCTCCACAAGATCTAGTGCTATGGTGGTATAGTAAGCTCGTACTGTGGTAGACGCGACACGGGTAGGACCATCAG",
    "TAATAAGGATAGTGCGAAAGCTCACAGACCACTGCCTATAGGGGGTGCTTACTTTTACAAAAAGCGACTGTCAGTATAACCCCACGAGGATTCGAAAAGGTGAACCGACCCAGACGATCCGGAGGCACGGGCCTCAAAGCCGCGACACGACGGCTGTCGGCCGGTAACAGTAACCCCGGAGTGAACTCCTATGGGGCTGG",
    "ATAGAACAGCCCTGGTGGGCCCCATCAGCAACCCGAATACGTGGCTTTTCGGGAGGCGGCCGGAGGGGCGATGTCTTCCACTATTCGAGGCCGTTCGTTAATACTTGTTGCGTTCCTAGCCGCTATATTTGTCTCTTTGCCGACTAATGTGGACAAGCACACCATAGCCATTTATCGGAGCGCCTCGGAATACGGTATGA",
]


print fwdp(seqlist)
