name: tests

on:
  push:
    branches: [ black ]
  pull_request:
    branches: [ black ]

jobs:
  build:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.8", "3.7", "3.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: false
          add-pip-as-python-dependency: true
          activate-environment: pydna_test_environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge, defaults
          environment-file: pydna_test_environment.yml
          use-only-tar-bz2: true
      - name: Install from source
        # This is required for the pre-commit tests
        shell: pwsh
        run: pip install .
      - name: Test with pytest
        shell: pwsh
        run: python run_test.py
