name: Tests & Coverage
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'windows-latest' ]
        python-version: ["3.10", "3.9", "3.8", "3.7"]
        include:
        - os: ubuntu-latest
          python-version: "3.7"
        - os: ubuntu-latest
          python-version: "3.8"
          codecov: true
        - os: ubuntu-latest
          python-version: "3.9"
        - os: ubuntu-latest
          python-version: "3.10"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}

      - name: Install conda environment from pydna_test_environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: pydna_test_environment.yml

      - name: micromamba info
        shell: bash -l {0}
        run: micromamba info

      - name: micromamba list
        shell: bash -l {0}
        run: micromamba list

      - name: Install from source
        shell: bash -l {0}
        run: pip install --editable . --no-deps

      - name: python run_test.py
        shell: bash -l {0}
        run: python run_test.py

      - name: Upload coverage to Codecov
        if: (matrix.codecov)
        uses: codecov/codecov-action@v1.0.13
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
