name: Conda Package Build
on:
  release:
    types: [published]
jobs:
  build:
    name: Build noarch python package
    runs-on: ubuntu-latest
    steps:

      - name: ⬇️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 🌰 Cache conda
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: conda-ubuntu-latest-python-build-${{ hashFiles('environment-ci.yml') }}

      - name: 🌍 Install conda environment from pydna_build_environment with miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pydna_build_environment
          environment-file: pydna_build_environment.yml

      - name: mamba info --all
        shell: bash -l {0}
        run: mamba info --all

      - name: mamba config
        shell: bash -l {0}
        run: conda config --set anaconda_upload yes

      - name: Git tag
        shell: bash -l {0}
        run: git describe --tags

      - name: 🔩 Check version
        shell: bash -l {0}
        run: poetry version

      - name: 🔩 Set version
        shell: bash -l {0}
        run: poetry dynamic-versioning

      - name: 🔩 Check version
        shell: bash -l {0}
        run: poetry version

      - name: Git tag
        shell: bash -l {0}
        run: git describe --tags

      - name: 🔩 Build conda package with mamba
        shell: bash -l {0}
        run: mamba build . --no-test --no-include-recipe --dirty --token ${{ secrets.ANACONDATOKEN }}
