name: Tests & Coverage
on:
  push:
    branches: [ testrelease ]
  pull_request:
    branches: [ testrelease ]
jobs:
  build:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.8", "3.7", "3.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Cache conda
        uses: actions/cache@v2.1.1
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.7.0
        with:
          auto-update-conda: true
          auto-activate-base: false
          add-pip-as-python-dependency: true
          activate-environment: pydna_test_environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge, defaults
          environment-file: pydna_test_environment.yml
          use-only-tar-bz2: true

      - name: Test with pytest
        shell: bash -l {0}
        run: python run_test.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          files: ./coverage1.xml,./coverage2.xml
          directory: ./coverage/reports/
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.gz
