name: Build for TESTPyPI
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && contains(github.ref, '/testpypi')
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
          plugins: "poetry-dynamic-versioning[plugin]"
